version: "3.3"
services:
  db:
    image: "postgres:11"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=pepppermint-dev
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=peppermint
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_local_dev:/var/lib/postgresql/data

  mailhog:
    image: jcalonso/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://pepppermint-dev:12345@db:5432/peppermint"
    depends_on:
      - db
    ports:
      - "5003:5003"
volumes:
  postgres_data_local_dev:
